# Generated by Django 5.0.6 on 2024-06-08 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_da_semana', models.CharField(max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cronograma.materia')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cronograma.professor')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cronograma.sala')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cronograma.turma')),
            ],
        ),
    ]
